import { createHash } from 'node:crypto';
import { mkdir, readFile, readdir, stat, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import sharp from 'sharp';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const incomingDir = path.join(root, 'incoming/images');
const generatedContentDir = path.join(root, 'src/content/works/generated');
const imageOutDir = path.join(root, 'public/media/images/auto');
const thumbOutDir = path.join(root, 'public/media/thumbnails/auto');
const sourceExtensions = new Set([
  '.avif',
  '.gif',
  '.jpeg',
  '.jpg',
  '.png',
  '.tif',
  '.tiff',
  '.webp',
]);

await Promise.all([
  mkdir(incomingDir, { recursive: true }),
  mkdir(generatedContentDir, { recursive: true }),
  mkdir(imageOutDir, { recursive: true }),
  mkdir(thumbOutDir, { recursive: true }),
]);

const files = (await readdir(incomingDir, { withFileTypes: true }))
  .filter((entry) => entry.isFile())
  .map((entry) => entry.name)
  .filter((name) => sourceExtensions.has(path.extname(name).toLowerCase()))
  .sort((a, b) => a.localeCompare(b));

if (files.length === 0) {
  console.log('No images found in incoming/images.');
  process.exit(0);
}

let imported = 0;

for (const file of files) {
  const sourcePath = path.join(incomingDir, file);
  const source = await readFile(sourcePath);
  const checksum = createHash('sha256').update(source).digest('hex');
  const sourceStat = await stat(sourcePath);
  const parsed = parseImageName(file);
  const slug = parsed.slug;
  const date = parsed.date ?? toDateOnly(sourceStat.mtime);
  const updatedAt = toDateOnly(sourceStat.mtime);
  const title = parsed.title;
  const description = `AI-generated image imported from ${file}.`;
  const fullImagePath = path.join(imageOutDir, `${slug}.webp`);
  const thumbPath = path.join(thumbOutDir, `${slug}.webp`);
  const contentPath = path.join(generatedContentDir, `${slug}.mdx`);

  await sharp(sourcePath)
    .rotate()
    .resize({ width: 1800, withoutEnlargement: true })
    .webp({ quality: 84 })
    .toFile(fullImagePath);

  await sharp(sourcePath)
    .rotate()
    .resize({ width: 900, height: 675, fit: 'cover', withoutEnlargement: true })
    .webp({ quality: 78 })
    .toFile(thumbPath);

  if (await shouldWriteMdx(contentPath, checksum)) {
    await writeFile(
      contentPath,
      makeMdx({
        title,
        slug,
        description,
        date,
        updatedAt,
        file,
        checksum,
      }),
    );
  }

  imported += 1;
}

console.log(
  `Synced ${imported} image${imported === 1 ? '' : 's'} from incoming/images.`,
);

function parseImageName(file) {
  const extension = path.extname(file);
  const base = path.basename(file, extension);
  const dateMatch = base.match(/^(\d{4}-\d{2}-\d{2})[-_\s]+(.+)$/);
  const date = dateMatch?.[1];
  const nameWithoutDate = dateMatch?.[2] ?? base;
  const slug = slugify(nameWithoutDate) || slugify(base);
  const title = titleize(nameWithoutDate);

  return { date, slug, title };
}

function slugify(value) {
  return value
    .normalize('NFKD')
    .replace(/[\u0300-\u036f]/g, '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

function titleize(value) {
  const cleaned = value.replace(/[_-]+/g, ' ').replace(/\s+/g, ' ').trim();

  if (!cleaned) return 'Untitled AI Image';

  return cleaned.replace(/\b[a-z]/g, (letter) => letter.toUpperCase());
}

function toDateOnly(date) {
  return date.toISOString().slice(0, 10);
}

function yamlString(value) {
  return `'${String(value).replace(/'/g, "''")}'`;
}

async function shouldWriteMdx(contentPath, checksum) {
  try {
    const existing = await readFile(contentPath, 'utf8');
    return !existing.includes(`sha256: '${checksum}'`);
  } catch {
    return true;
  }
}

function makeMdx({
  title,
  slug,
  description,
  date,
  updatedAt,
  file,
  checksum,
}) {
  const alt = `AI-generated image titled ${title}.`;

  return `---
title: ${yamlString(title)}
slug: ${yamlString(slug)}
description: ${yamlString(description)}
type: 'image'
status: 'published'
createdAt: '${date}'
updatedAt: '${updatedAt}'
thumbnail: '/media/thumbnails/auto/${slug}.webp'
thumbnailAlt: ${yamlString(alt)}
heroImage: '/media/images/auto/${slug}.webp'
heroImageAlt: ${yamlString(alt)}
tools: []
tags:
  - 'ai-generated'
license: 'CC BY-NC 4.0'
featured: false
draft: false
provenance:
  source: ${yamlString(`incoming/images/${file}`)}
  notes: 'Generated by scripts/sync-images.mjs.'
  sha256: '${checksum}'
---

This entry was generated from \`incoming/images/${file}\`.

Add notes here only if this image grows into a fuller project record.
`;
}
